#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Michael Utz"
email = "michael@theutz.com"

[ui]
default-command = "status"
diff-editor = ":builtin"
pager = ":builtin"

[aliases]
gp = ['git', 'push']
gf = ["git", "fetch"]
bc = ["bookmark", "create"]
bm = ["bookmark", "move"]
d = ["desc", "-m"]
c = ["commit", "-m"]
s = ["split"]

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519"
