#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Michael Utz"
email = "michael@theutz.com"

[ui]
default-command = "log"
diff-editor = ":builtin"

[aliases]
gp = ['git', 'push']
bm = ["bookmark", "move"]
d = ["diff"]
gf = ["git", "fetch"]
cm = ["commit", "-m"]

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519"
