theme = "rose_pine"

[editor]
line-number = "relative"
mouse = true
shell = [
    "nu",
    "-c",
]
cursorline = true
cursorcolumn = true
rulers = [120]
bufferline = "always"
text-width = 120
clipboard-provider = "pasteboard"

[editor.whitespace]
render = "all"

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
