[env]
XDG_CONFIG_HOME = '{{xdg_config_home}}'
XDG_DATA_HOME = '{{xdg_data_home}}'
XDG_STATE_HOME = '{{xdg_state_home}}'
XDG_CACHE_HOME = '{{xdg_cache_home}}'
_.path = [
  "/opt/homebrew/sbin",
  "/opt/homebrew/bin",
  ".local/bin",
  "bin",
  "/usr/local/bin",
  "{{xdg_config_home}}/composer/vendor/bin",
]
_.file = "~/.config/mise/env.sops.yaml"
EDITOR = "nvim"
VISUAL = "nvim"
LESS = "-g -i -M -R -S -w -X -z-4"
LESSOPEN = "|/usr/bin/env lesspipe.sh %s 2>&-"
PAGER = "less"
BROWSER = "open"
LANG = "en_US.UTF-8"
EZA_ICONS_AUTO = "1"
MANPAGER = "nvim -c +Man!"
MANWIDTH = "999"
TZ_LIST = "US/Pacific;US/Central;US/Eastern;UTC;Europe/Istanbul"
PET_GITHUB_ACCESS_TOKEN = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdTcvSjdEN0xUUjErRmkrQVFaenFNZjFzVGZJemZSZFRQb0RjdEVOdUcwCmE4bklxYlo3WnNCSFRaZVEraWl5TEtpUm95N2x0OUdZbHc1RlFLUEdjb3cKLT4gc3NoLWVkMjU1MTkgUUt0Um5BIEVwa1V4ejIwa3BabDl3aERLcXNkYTBuVDhTaVZ4aDh6bCtoM21CdWJ3aG8KTVFYb0F5N3NaS0x4MnNNQUZTYTFCeUZFeksxWGt4VGh1bWkzZG1pMUxwdwotPiBNXidYLWdyZWFzZSBaWCpEST8gQGVHfiggYjxAfDdlTQpraDNFRER2NHo5b2RKMlkyUzMvYkc0NVg1RGFveEZCVlFpT1huLzhoYkFRZVAxbWV1R1puMEhkbFlGTUhRdGo2CjRnCi0tLSBpeVhKdm83UXRaWVRWNlgyb2hzSC9qL1dxOHVnQU9JakJTWCt5UG1XemFzCrBeJxUdru7hRFJ1wZcqVcYsSM1E4X5b1nACtragLcxMGvveWBZ8vJlo4UmGhM29l186/3SGNPJ/Xo7Du7sBhjmB1yyPPdzryw" }

[tools]
aqua = "latest"
bat = "latest"
bat-extras = "latest"
carapace = "latest"
eza = "latest"
fzf = "latest"
gum = "latest"
mods = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
ubi = "latest"
usage = "latest"
zoxide = "latest"
yazi = "latest"
fastfetch = "latest"
vivid = "latest"
go = "latest"
chezmoi = { version = "latest", postinstall = """
chezmoi completion zsh > ~/.local/functions/_chezmoi
""" }
fd = "latest"
gh = "latest"
lazydocker = "latest"
coreutils = "latest"
difftastic = "latest"
node = "latest"
sd = "latest"
doggo = "latest"
"ubi:peak/s5cmd" = "latest"
jujutsu-ui = "latest"
jujutsu = "latest"
uv = "latest"
"pipx:tmuxp" = "latest"
"ubi:42futures/firm" = "latest"
jjui = "latest"
glow = "latest"
"ubi:Skardyy/mcat" = "latest"
"ubi:unkn0wn-root/resterm" = "latest"
zellij = "latest"
"ubi:acheronfail/repgrep" = { version = "latest", exe = "rgr" }
"ubi:docker/docker-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:yaml-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"ubi:tamasfe/taplo" = "latest"
marksman = "latest"
lua-language-server = "latest"
"npm:vscode-langservers-extracted" = "latest"
golangci-lint-langserver = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:awk-language-server" = "latest"
"npm:bash-language-server" = "latest"
terraform-ls = "latest"
"ubi:sayanarijit/xplr" = "latest"
fnox = "latest"
"ubi:elliot40404/volgo" = "latest"
"ubi:superstarryeyes/bit" = "latest"
"npm:gitignore" = "latest"
dive = "latest"
claude = "latest"
codex = "latest"
scooter = "latest"
"ubi:achristmascarl/rainfrog" = "latest"
"cargo:nu_plugin_dns" = { version = "latest", locked = "true" }
"aqua:nushell/nushell" = "latest"
"ubi:owloops/updo" = "latest"
"ubi:ouch-org/ouch" = "latest"
ripgrep-all = "latest"
dua = "latest"
"ubi:sharkdp/pastel" = "latest"
"ubi:dalance/procs" = "latest"
sops = "latest"
gemini = "latest"
"ubi:chaqchase/lla" = "latest"
"ubi:oz/tz" = "latest"
"ubi:knqyf263/pet" = "latest"
"ubi:macchina-cli/macchina" = "latest"
ruby = "latest"
dust = "latest"

[settings]
experimental = true

[settings.age]
