[env]
XDG_CONFIG_HOME = '{{xdg_config_home}}'
XDG_DATA_HOME = '{{xdg_data_home}}'
XDG_STATE_HOME = '{{xdg_state_home}}'
XDG_CACHE_HOME = '{{xdg_cache_home}}'
_.path = [
  "/opt/homebrew/sbin",
  "/opt/homebrew/bin",
  ".local/bin",
  "bin",
  "/usr/local/bin",
  "{{xdg_config_home}}/composer/vendor/bin",
]
_.file = "~/.config/mise/env.sops.yaml"
EDITOR = "hx"
VISUAL = "hx"
LESS = "-g -i -M -R -S -w -X -z-4"
LESSOPEN = "|/usr/bin/env lesspipe.sh %s 2>&-"
PAGER = "less"
BROWSER = "open"
LANG = "en_US.UTF-8"
APPEARANCE_FILE = '''
{{- [xdg_state_home, "appearance"] | join_path() -}}
'''
APPEARANCE = '''
{{- read_file(path=env.APPEARANCE_FILE) | trim -}}
'''
EZA_ICONS_AUTO = "1"
MANPAGER = { value = "nvim -c +Man!", tools = true }
MANWIDTH = { value = "999", tools = true }
DELTA_FEATURES = { value = """{% if env.APPEARANCE == "light" %}+{% else %}+dark{% endif %}""", tools = true }
BAT_THEME = { value = """{% if env.APPEARANCE == "light" %}rose-pine-dawn{% else %}rose-pine{% endif %}""", tools = true }
DFT_BACKGROUND = { value = """{% if env.APPEARANCE == "light" %}light{% else %}dark{% endif %}""", tools = true }

[tools]
aqua = "latest"
bat = "latest"
bat-extras = "latest"
carapace = "latest"
eza = "latest"
fzf = "latest"
gum = "latest"
mods = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
ubi = "latest"
usage = "latest"
zoxide = "latest"
yazi = "latest"
fastfetch = "latest"
vivid = "latest"
go = "latest"
chezmoi = { version = "latest", postinstall = """
chezmoi completion zsh > ~/.config/zsh/functions/_chezmoi
""" }
fd = "latest"
gh = "latest"
lazydocker = "latest"
coreutils = "latest"
difftastic = "latest"
node = "latest"
sd = "latest"
doggo = "latest"
"ubi:peak/s5cmd" = "latest"
jujutsu-ui = "latest"
jujutsu = "latest"
uv = "latest"
"pipx:tmuxp" = "latest"
"ubi:42futures/firm" = "latest"
"cargo:nu_plugin_dns" = "latest"
jjui = "latest"
glow = "latest"
"ubi:Skardyy/mcat" = "latest"
"ubi:unkn0wn-root/resterm" = "latest"
zellij = "latest"
"ubi:acheronfail/repgrep" = { version = "latest", exe = "rgr" }
mc = "latest"
"ubi:docker/docker-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:yaml-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"ubi:tamasfe/taplo" = "latest"
marksman = "latest"
lua-language-server = "latest"
"npm:vscode-langservers-extracted" = "latest"
golangci-lint-langserver = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:awk-language-server" = "latest"
"npm:bash-language-server" = "latest"
terraform-ls = "latest"
"ubi:sayanarijit/xplr" = "latest"
fnox = "latest"
"ubi:elliot40404/volgo" = "latest"
"ubi:superstarryeyes/bit" = "latest"
"npm:gitignore" = "latest"
dive = "latest"
claude = "latest"
codex = "latest"
scooter = "latest"

[settings]
experimental = true
