["rose-pine.tmTheme"]
type = "archive-file"
url = "https://github.com/rose-pine/tm-theme/archive/refs/heads/main.zip"
path = "dist/rose-pine.tmTheme"
exact = false
stripComponents = 1
refreshPeriod = "168h"

["rose-pine-moon.tmTheme"]
type = "archive-file"
url = "https://github.com/rose-pine/tm-theme/archive/refs/heads/main.zip"
path = "dist/rose-pine-moon.tmTheme"
exact = false
stripComponents = 1
refreshPeriod = "168h"

["rose-pine-dawn.tmTheme"]
type = "archive-file"
url = "https://github.com/rose-pine/tm-theme/archive/refs/heads/main.zip"
path = "dist/rose-pine-dawn.tmTheme"
exact = false
stripComponents = 1
refreshPeriod = "168h"
